// Copyright 2017 NDP Systèmes. All Rights Reserved.
// See LICENSE file for full licensing details.

package generate

import (
	"fmt"
	"go/build"

	"github.com/hexya-erp/hexya/hexya/tools/logging"
)

const (
	// HexyaPath is the go import path of the base hexya package
	HexyaPath string = "github.com/hexya-erp/hexya"
	// ModelsPath is the go import path of the hexya/models package
	ModelsPath string = "github.com/hexya-erp/hexya/hexya/models"
	// TypesPath is the go import path of the hexya/models/types package
	TypesPath string = "github.com/hexya-erp/hexya/hexya/models/types"
	// GeneratePath is the go import path of this package
	GeneratePath string = "github.com/hexya-erp/hexya/hexya/tools/generate"
	// PoolPath is the go import path of the autogenerated pool package
	PoolPath string = "github.com/hexya-erp/hexya/pool"
)

var (
	log *logging.Logger
	// HexyaDir is the directory of the base hexya package
	HexyaDir string
	// ModelMixins are the names of the mixins declared in the models package
	ModelMixins map[string]bool = map[string]bool{
		"CommonMixin":    true,
		"BaseMixin":      true,
		"ModelMixin":     true,
		"TransientMixin": true,
	}
)

func init() {
	log = logging.GetLogger("tools/generate")
	hexyaPack, err := build.Import(HexyaPath, ".", build.FindOnly)
	if err != nil {
		panic(fmt.Errorf("Error while getting Hexya root path: %s", err))
	}
	HexyaDir = hexyaPack.Dir
}
