= Installing Hexya
Author Nicolas Piganeau
:prewrap!:
:toc:
:sectnums:

== Introduction
Since Hexya is a modular ERP at compile time, it is only distributed as source
code. The following instructions will guide you through the process of
downloading the source code, setting up your configuration and compile Hexya.

== Prerequisites

=== Install Go
First of all, you need to install the Go SDK. Follow the instructions on the
Go website to install on your platform: https://golang.org/dl/ .

Then setup your Go workspace and define your `$GOPATH` environment variable as
described here: https://golang.org/doc/code.html#Workspaces

NOTE: It is assumed in the document that you added `$GOPATH/bin` to your
`$PATH`.

=== Install lessc

Hexya needs the less compiler `lessc` to be installed.

If you have `npm`, you can use:

```
$ npm install -g less
```

On Debian/Ubuntu you can alternately run:

```
$ sudo apt-get install node-less
```

== Download

=== Download Hexya
Hexya uses the standard go toolchain. Download Hexya with the following command:

[source,shell]
----
go get github.com/hexya-erp/hexya
----

This will download hexya and its dependencies in your workspace and compile the
`hexya` command.

=== Download Hexya modules
Hexya modules are distributed as Go packages. They can be downloaded with
`go get` too. For instance, to get the official addons:

[source,shell]
----
go get -d github.com/hexya-erp/hexya-base
go get -d github.com/hexya-erp/hexya-addons
----

NOTE: Discard any message about no buildable Go code

== Create a project
You need to create a project to run a Hexya server. Your project will hold your
specific configuration, in particular the modules to install.

=== Download Demo Project
If you want to evaluate Hexya, you can download the `hexya-demo` project.

[source,shell]
----
go get github.com/hexya-erp/hexya-demo
----

=== Creating a custom project
To create a custom project, create a go package with the following structure:

[source,shell]
----
<projectDir>/
    config/
        config.go
----

IMPORTANT: Since this is a go package, `<projectDir>` *MUST* be in a
subdirectory of `$GOPATH/src`.

Edit the `config.go` file and make it look like the following, adding one line
per module to install in your Hexya instance in the `import` stanza:

[source,go]
----
package config

import (
    _ "github.com/hexya-erp/hexya-addons/sale"
    _ "github.com/hexya-erp/hexya-addons/stock"
    _ "github.com/hexya-erp/hexya-addons/purchase"
    _ "github.com/my-partner/my-super-module"
)
----

NOTE: The leading underscore before each module import path makes the file
valid Go.

=== Generate Hexya

This step will generate some source code that depends on the modules you
selected in the previous step. It must be performed after each modification
of the configuration from inside the project directory.

[source,shell]
----
cd <projectDir>
hexya generate
----

Type `hexya help generate` for the list of available options:

[source,shell]
----
$ hexya help generate
Generate the source code of the pool package which includes the definition of all the models.
Additionally, this command creates the startup file of the project.
This command must be rerun after each source code modification, including module import.

  projectDir: the directory in which to find the go package that imports all the modules we want.
              If not set, projectDir defaults to the current directory

Usage:
  hexya generate [projectDir] [flags]

Flags:
      --empty         Generate an empty pool package. When set projectDir is ignored.
  -t, --test string   Generate pool for testing the module in the given source directory. When set projectDir is ignored.

Global Flags:
  -c, --config string        Alternate configuration file to read. Defaults to $HOME/.hexya/
      --db-driver string     Database driver to use (default "postgres")
      --db-host string       The database host to connect to. Values that start with / are for unix domain sockets directory (default "/var/run/postgresql")
      --db-name string       Database name (default "hexya")
      --db-password string   Database password. Leave empty when connecting through socket
      --db-port string       Database port. Value is ignored if db-host is not set (default "5432")
      --db-user string       Database user. Defaults to current user
      --debug                Enable server debug mode for development
  -l, --log-file string      File to which the log will be written
  -L, --log-level string     Log level. Should be one of 'debug', 'info', 'warn', 'error' or 'crit' (default "info")
  -o, --log-stdout           Enable stdout logging. Use for development or debugging.
----

== Synchronise database

=== Setup Postgresql

For now Hexya only supports Postgresql. Here is the quick setup for evaluating
Hexya. Please refer to Postgresql documentation for finer setup.

==== Create a postgres user
On Linux, use your distribution's package, then create a postgres user named
like your login:

[source,shell]
----
$ sudo su - postgres -c "createuser -s $USER"
----
Because the role login is the same as your unix login unix sockets can be use
without a password.

==== Create a hexya database
[source,shell]
----
$ createdb hexya
----

=== Synchronise database schema with models

This step will synchronise the database with the models defined.

[source,shell]
----
cd <projectDir>
hexya updatedb -o
----

Type `hexya help updatedb` for the list of available options:

[source,shell]
----
$ hexya help updatedb
Synchronize the database schema with the models definitions.

Usage:
  hexya updatedb [flags]

Global Flags:
  -c, --config string        Alternate configuration file to read. Defaults to $HOME/.hexya/
      --db-driver string     Database driver to use (default "postgres")
      --db-host string       The database host to connect to. Values that start with / are for unix domain sockets directory (default "/var/run/postgresql")
      --db-name string       Database name (default "hexya")
      --db-password string   Database password. Leave empty when connecting through socket
      --db-port string       Database port. Value is ignored if db-host is not set (default "5432")
      --db-user string       Database user. Defaults to current user
      --debug                Enable server debug mode for development
  -l, --log-file string      File to which the log will be written
  -L, --log-level string     Log level. Should be one of 'debug', 'info', 'warn', 'error' or 'crit' (default "info")
  -o, --log-stdout           Enable stdout logging. Use for development or debugging.
----

== Running Hexya

Hexya is launched by the `hexya server` command from inside the project directory.

[source,shell]
----
cd <projectDir>
hexya server -o
----

Type `hexya help server` to get the list of available options:

[source,shell]
----
$ hexya help server
Start the Hexya server of the project in 'projectDir'.
If projectDir is omitted, defaults to the current directory.

Usage:
  hexya server [projectDir] [flags]

Flags:
  -i, --interface string   Interface on which the server should listen. Empty string is all interfaces
  -p, --port string        Port on which the server should listen. (default "8080")

Global Flags:
  -c, --config string        Alternate configuration file to read. Defaults to $HOME/.hexya/
      --db-driver string     Database driver to use (default "postgres")
      --db-host string       The database host to connect to. Values that start with / are for unix domain sockets directory (default "/var/run/postgresql")
      --db-name string       Database name (default "hexya")
      --db-password string   Database password. Leave empty when connecting through socket
      --db-port string       Database port. Value is ignored if db-host is not set (default "5432")
      --db-user string       Database user. Defaults to current user
      --debug                Enable server debug mode for development
  -l, --log-file string      File to which the log will be written
  -L, --log-level string     Log level. Should be one of 'debug', 'info', 'warn', 'error' or 'crit' (default "info")
  -o, --log-stdout           Enable stdout logging. Use for development or debugging.
----

You can now access the Hexya server at http://localhost:8080

Default credentials are :

- Login: `admin`
- Password: `admin`
