= Models API
Author Nicolas Piganeau
:prewrap!:
:toc:

== Introduction

The models API allows modules to interact with YEP's models and records. This
API is mainly an ORM but with additional features needed for business logic.
Developers familiar with Odoo's ORM should find many similarities with the
latter.

Special care has been put in YEP's model API to ease development. In
particular:

* Almost no reflection so that a standard Go IDE can propose relevant
inspections and autocompletion.
* Type safety by preferring structs to maps and almost never use string
references so that most mistakes can be spotted at compile time.

== RecordSets

=== Records and RecordSets types

Interaction with models and records is performed through RecordSets, a sorted
set of Records of the same model. Methods defined on a model are executed on a
RecordSet.

Each model has its own RecordSet Go type named by appending "Set" to the
model's name (e.g. the RecordSet type for the `ResPartner` model is called
`ResPartnerSet`). All RecordSet types implement the `RecordSet` interface, but
also a whole set of methods with defined names but which differ by the
parameters or return values types. For example, all RecordSets implement a
`Create` method but each take a Record struct of its model type and return its
own type.

Each model has also its own Record Go type which has the same name as its
model's name. A Record type is simply a struct with all the fields of the model
whether they are stored into the database or computed on the fly. Record types
are used to read and write values to RecordSets.

All Record and RecordSet types live in the `pool` package.

A constant for the field name of each model of type `models.FieldName` exists
in the `pool` package in the form `pool.__ModelName_FieldName__`.

=== Using RecordSets

RecordSets are self-querying. One should initialize an empty RecordSet call
`search()` on it to populate it from the database. RecordSets implement lazy
loading, so that data is actually queried only when needed.

An empty RecordSet instance of a model `ModelName` can be instantiated by
calling `pool.NewModelNameSet(env Environment)`.

=== Common RecordSet Methods

The following methods can be called RecordSet instances.

[NOTE]
====
A parameter or return value of type `RecordSetType` means the actual type of
the RecordSet for this model (not an interface).

A parameter or return value of type `RecordType` means the actual type of the
Record struct for this model.
====

==== Data Access Methods

`*First() RecordType*`::
Returns a copy of the first Record of the RecordSet. It returns an empty
RecordType if the RecordSet is empty.

`*All() []RecordType*`::
Returns all Records of the RecordSet as a slice of RecordType. It returns an
empty slice if the RecordSet is empty.

`*Read(fields []string) []FieldMap*`::
Returns all Records of the RecordSet as a slice of FieldMap. It returns an
empty slice if the RecordSet is empty.

RecordSets implement type safe getters and setters for all fields of the
Record struct type.

`*__FieldName__() __FieldType__*`::
Getter for the field called `__FieldName__` of type `__FieldType__` of the
`First()` Record of the RecordSet. Call to the getter will make a call to
`Read()` first if the field is not loaded in the RecordSet's cache.
+
It returns the Go zero value of the type if it is called on an empty RecordSet.

`*Set__FieldName__(value __FieldType__)*`::
Setter for the field called `__FieldName__` of type `__FieldType__`. If the
RecordSet has several Records, all of them will be updated. Each call to the
setter makes an update query in the database.
+
It panics if it is called on an empty RecordSet.

NOTE: The `__FieldType__` of a relation field (i.e. many2one, ...) is a
RecordSet of the type of the related model.

==== CRUD Methods

`*Create(data *RecordType) RecordSetType*`::
Insert a new record in the database with the given data and returns the
inserted Record. Fields which are not given a value are set to the type's zero
value.

[source,go]
----
customer := pool.NewResPartnerSet(env).Create(pool.ResPartner{
    Name: "Jane Smith",
    Email: "jsmith@example.com",
    Position: "Sale's Manager",
})
fmt.Println(customer.Name())
// Returns:
// Jane Smith
----

IMPORTANT: `Create` is meant to be called on an empty RecordSet.
Thus, it discards any value already loaded.

`*Write(data *RecordType, fieldsToUnset ...models.FieldName) bool*`::
Update records in the database with the given data. Updates are made with a
single SQL query. Fields in `fieldsToUnset` are first set to their Go zero
value, then all non-zero values of data are updated.

[source,go]
----
partner := pool.NewResPartnerSearch(env).Filter("Company.Name", "=", "NDP Systèmes")
partner.Write(pool.ResPartner{
    Lang: "fr_FR",
})
----

IMPORTANT: As said above, zero values in the `data` struct fields will *NOT* be
updated. If you are not sure whether the values you pass in the `data` struct
are zero values or not (e.g. when setting from a variable), include their
`FieldName` in the `fieldsToUnset` to be sure the value will be correctly
updated in case it is a zero value.

`*Unlink() bool*`::
Deletes the database records that are linked with this RecordSet.

`*Load(fields ...models.FieldName) RecordSetType*`::
Populates this RecordSet with the data from the database matching the current
search condition. If fields are given, only those fields are fetched and the
other fields of the Records are set to their `go` zero value.

NOTE: Call to `Load()` is optional. It will be automatically called (without
fields arguments) on the first call to a getter or when calling `Records()`.

TIP: Calling `Load()` with fields arguments before any other call allows to
finely control which fields will be queried from the database since subsequent
calls to a getter will not call `Read()` again if the value is already loaded.

[source,go]
----
partners := pool.NewResPartnerSet(env)
partners.Filter("Name", "ilike", "John").Read(pool.ResPartner_Name, pool.ResPartner_Birthday)

// The following lines will not load from the database, but use
// the values cached in the RecordSet.
for _, p := range partners.Records() {
    fmt.Println(p.Name(), p.Birthday())
}
// Returns:
// John Smith 1982-06-03
// John Doo 1975-01-06
----

==== Search Methods

`*Search(condition *models.Condition) RecordSetType*`::
Apply the given search condition to the given RecordSet.
A new Condition instance can be created with `models.NewCondition()`.

[source,go]
----
cond := models.NewCondition().And(pool.ResUsers_Email, "ilike", "example.com").Or(pool.ResUsers_Email, "ilike", "example.net")
users := NewResUsersSet(env).Search(cond)
----

====
.Available methods on Condition type
* `And(field models.FieldName, operator string, value interface{})`
* `AndNot(field models.FieldName, operator string, value interface{})`
* `AndCond(condition *models.Condition)`
* `Or(field models.FieldName, operator string, value interface{})`
* `OrNot(field models.FieldName, operator string, value interface{})`
* `OrCond(condition *models.Condition)`
====

`*Filter(field models.FieldName, operator string, value interface{}) RecordSetType*`::
`Filter` is a shortcut for `Condition(models.NewCondition().And(field,
operator, value))`.

`*Exclude(field models.FieldName, operator string, value interface{}) RecordSetType*`::
`Exclude` is a shortcut for `Condition(models.NewCondition().AndNot(field,
 operator, value))`.

`*SearchCount() int*`::
Return the number of records matching the search condition.

`*NameSearch(params models.NameSearchParams) RecordSetType*`::
Search for records that have a display name matching the given
`Name` pattern when compared with the given `Operator`, while also
matching the optional search domain (`Args`).
+
This is used for example to provide suggestions based on a partial
value for a relational field. Sometimes be seen as the inverse
function of `NameGet` but it is not guaranteed to be.

====
.NameSearchParams
[source, go]
----
type NameSearchParams struct {
	Args     Domain      `json:"args"`
	Name     string      `json:"name"`
	Operator string      `json:"operator"`
	Limit    interface{} `json:"limit"`
}

----
====

`*Limit(n int) RecordSetType*`::
Limit the search to `n` results.

`*Offset(n int) RecordSetType*`::
Offset the search by `n` results.

`*OrderBy(exprs ...string) RecordSetType*`::
Order the results by the given expressions. Each expression is a string with a
valid field name and optionally a direction.

[source,go]
----
users := pool.NewResUsersSet(env).OrderBy("Name ASC", "Email DESC", "ID")
----

==== RecordSet Operations

`*Ids() []int64*`::
Return a slice with all the ids of this RecordSet. Performs a lazy loading of
the RecordSet if it is not already loaded.

`*Env() *Environment*`::
Returns the RecordSet's Environment.

`*Len() int*`::
Returns the number of records in this RecordSet.

`*Record(i int) RecordSetType*`::
Returns a new RecordSet with only the i^th^ Record inside.

`*Records() []RecordSetType*`::
Returns a slice of RecordSets, each with only one Record of the current
RecordSet.

`*EnsureOne()*`::
Check that this RecordSet contains only one Record. Panics if there are more
than one Record or if there are no Records at all.

`*Filtered(fn func(RecordType) bool) RecordSetType*`::
Select the records in this RecordSet such that fn(Record) is true, and return
them as a RecordSet.

`*Sorted(key func(Record) interface{}) RecordSetType*`::
Returns a sorted copy of this RecordSet. `key(record)` should return a
sortable value on which the RecordSet will be sorted.
+
The Sort is not guaranteed to be stable.

`*Union(other RecordSetType) RecordSetType*`::
Returns a new RecordSet that is the union of this RecordSet and the given
`other` RecordSet. The result is guaranteed to be a set of unique records.

== Environment

The Environment stores various contextual data used by the ORM: the database
transaction (for database queries), the current user (for access rights
checking) and the current context (storing arbitrary metadata).

The usual way to get the current Environment is to call `Env()` on a RecordSet.

The Environment is immutable. It can be customized with the following methods
to be applied on the RecordSet.

`*Sudo(uid ...int64) RecordSetType*`::
Call the next method as Super User. If uid is given, use the given user id
instead.

[source,go]
----
noReplyUser := pool.NewResUsers(env).Filter("Email", "=", "no-reply@ndp-systemes.fr").Limit(1)
partners := pool.NewResPartnerSet(env).Filter("Name", "ilike", "John")

partners.Sudo(noReplyUser.ID()).SendConfirmationEmail()
----

`*WithEnv(env *Environment) RecordSetType*`::
Returns a copy of the current RecordSet with the given Environment.

`*WithContext(key string, value interface{}) RecordSetType*`::
Returns a copy of the current RecordSet with its context extended by the
given key and value.

`*WithNewContext(context *tools.Context) RecordSetType*`::
Returns a copy of the current RecordSet with its context replaced by the
given one.

== Creating / extending models

When developing a YEP module, you can create your own models and/or
extend in place existing models created by other modules.

[IMPORTANT]
====
After creating or modifying a model, you must run `yep-generate` to
generate the types in the `pool` package before starting the YEP server.

Running `yep-generate` will also allow you to obtain code completion and
inspection on the newly created types.
====

=== Creating a new model
`*models.CreateModel(modelName string, options ...Option)*`::

Creates a new model with the given `modelName`.

[source,go]
----
models.CreateModel("Course")
----
Available options are:

- `models.TransientModel`: set this model as transient. Transient models
records are periodically removed from the database. They are mainly used
for wizards.

=== Extending a model
Models can be extended by 3 different ways:

Extension::
Directly add fields and methods to existing models.

Mix In::
Add all fields and methods from a model to another model.

Embedding::
Allow direct access to all fields of another model. Embedding only applies to
fields, not methods.

==== Model Extension
`*models.ExtendModel(modelName string, dataStructPtr interface{})*`::
Extend a model by adding fields of `dataStructPtr` to the model.

See also <<Defining methods>> to see how to add or override methods in a model.

==== Model Mix In
`*models.MixInModel(targetModel, mixInModel string)*`::
Extend the `targetModel` by importing all fields and methods of `mixInModel`.

If a field name conflicts with an existing field name in the model, then:

.Field overriding rules
- Fields defined in the target model override fields defined in the mixin model
- Fields defined in an mixin override fields defined in another mixin imported
before.

If a method name conflicts with an existing method name in the model, then:

.Method overriding rules
- Methods defined in the target model extend methods of the mixin model. Use
`Super()` in the target model implementation to access the implementation of
the mixin.
- Methods defined in a mixin extend methods defined of another mixin imported
before.

NOTE: When mixing in a model, the database columns are copied into the table of
the target model, resulting in an independent model. However, all extensions of
the mixin model are taken into account and apply to all the target models, even
if the extension has been defined after the mixing in.

==== Model Embedding
Model embedding allows a model to read fields of another model just as if they
were normal fields of the model.

To embed a model, define a `many2one` field pointing at the model to embed and
add the `embed` tag to it.

NOTE: Embedding does not allow direct access to the embedded model methods.

=== Fields declaration

Models fields are defined through structs with annotated fields, as in the
example below:

[source,go]
----
models.ExtendModel("Course", new(struct {
    Name      string             `yep:"string(Name);help(This is the name of the course);required"`
    Date      models.DateTime    `yep:"string(Date of the Course)"`
    Teacher   pool.ResPartnerSet `yep:"string(Teacher);type(many2one)"`
    Date      models.DateTime    `yep:"required"`
    Attendees pool.ResPartnerSet `yep:"string(Attendees);type(many2many)"`
})
----

==== Struct field annotations

The following tags can be used to annotate fields. All are to be set inside a
`yep` annotation, separated by a semicolon. Where applicable tag parameters
have to be entered directly, without inverted commas.

===== Field type tags

`type(__value__)`::
Defines the type of the field. In most cases, it is implied from the field's Go
type, but it must be specified in the following cases:
====
Relational fields::
Allowed types are `one2one`, `many2one`, `one2many`, `many2many`
Special string types::
* `text` for multiline texts
* `html` for html strings that must be parsed as such
* `binary` for binary data stored in the database
* `selection` for text data that is limited to a few values
====

`fk(__value__)`::
Set the foreign key field name in the related model for `one2many` relations.

`comodel(__value__)`::
Set the other model for a relation field. This tag is used only in low level
API. The comodel is normally deduced from the type of the struct field.

`m2m_relmodel(__value__)`::
Set the name of the intermediate model for a `many2many` relation. This tag
is mandatory only if there are several `many2many` relations between the two
models.

`m2m_ours(__value__)`::
In a `many2many` relation, set the name of the field of the intermediate model
that points to this (our) model. This tag is mandatory only if the `many2many`
relation is pointing to the same model.

`m2m_theirs(__value__)`::
In a `many2many` relation, set the name of the field of the intermediate model
that points to the other (their) model, i.e. the model defined by `comodel`.
This tag is mandatory only if the `many2many` relation is pointing to the
same model.

`selection(__value__)`::
Comma separated list of tuples `__key__|__DisplayString__` for `selection`
type.

`size(__value__)`::
Maximum size for the `string` type in database.

`digits(__value__)`::
Sets the decimal precision to a Go `float` type to store as a decimal type in
database. `__value__` must be a `total, decimal` pair.

`json(__value__)`::
Field's json value that will be used for the column name in the database and
for json serialization to the client.

===== Field's metadata tags

`string(__value__)`::
Field's label inside the application.
`help(__value__)`::
Field's help typically displayed as tooltip.

===== Field's modifiers tags

`required`::
Defines the field as required (i.e. not null).

`optional`::
Defines the field as optional. This is the default, the tag exists to override
existing fields.

`unique`::
Defines the field as unique in the database table.

`not-unique`::
Unsets the `unique` attribute for this field. This is the default.

`index`::
Creates an index on this field in the database.

`nocopy`::
Fields marked with this tag will not be copied when a record is duplicated.

`copy`::
Unset the `nocopy` tag.

`group_operator(__value__)`::
`__value__` must be a valid database function that will be used on this
field when aggregating the model. It defaults to `sum`.

===== Computed fields tags

`compute(__value__)`::
Declares this field as a computed field. `__value__` must be the name of a
method on this RecordSet with the following signature, which returns a
Record with the values to update and a slice of field names to unset.

[source,go]
----
func (RecordSetType) (RecordType, []models.FieldName)
----

`related(__path__)`::
Declares this field as a related field, i.e. a field that is automatically
synchronized with another field. `__path__` must be a path string to the
related field starting from the current RecordSet
(e.g. `"Customer.Country.Name"`).

`store`::
For a `computed` or `related` field, if `store` tag is set, then the field
will be stored into the database. For `computed` fields, recomputation will
be triggered by the data in the `depends` tag.
+
Storing a computed or related field allows to make queries on their values and
speeds up reading of the RecordSet. However, the updates can be slowed down,
especially when multiple triggers are fired at the same time.

`unstore`::
Unset the `store` tag on this field. This is the default.

`depends(__paths__)`::
Defines the fields on which to trigger recomputation of this field. This is
relevant only for `computed` fields with the `store` tag set.
+
`__paths__` must be a comma separated list of paths to fields used in the
computation of this field. Paths may go through `one2many` or `many2many`
fields. In this case all the fields that would match will be used as triggers.

`embed`::
Embed the model of the related field into this model. This field must be a
`many2one` field.
+
When embedded, all the fields of the RecordSet pointed by this field
will be automatically added as `related` fields, so that they can be accessed
directly from this RecordSet.

NOTE: Only the fields of the embedded model will be accessible from this
model, not its methods.

=== Defining methods

Models' methods are defined in a module and can be overriden by any other
module, with the ability to call the original method with `Super`. This way,
methods can be overriden several times by different modules to iteratively
add new features.

Each override of a method is declared by a so-called "layer function" with the
actual implementation. Layer functions must meet the following constraints:

* Its first argument is the method's receiver. It must be of the
`__RecordSetType__` of the model.
* It may have at most one return value.
* It must panic when an error is encountered to force transaction rollback
(or solve the error directly if possible).

--

`*models.CreateMethod(modelName, methodName string, layerFunction interface{})*`::
Creates a new method on the given `modelName` with the given `methodName` and
apply the given `layerFunction` as first "layer function".

[source,go]
----
// PartnerUpdateBirthday updates this partner birthday.
func PartnerUpdateBirthday(rs ResPartnerSet, birthday time.Time) {
    rs.SetBirthday(Date(birthDay))
})

models.CreateMethod("ResPartner", "UpdateBirthday", PartnerUpdateBirthday)
----

[IMPORTANT]
====
The `modelName` and `methodName` attributes of `CreateMethod` *MUST* be string
literals for `yep-generate` to work correctly. Do *NOT* use variables or
constants here.

This limitation may be removed in a future version.
====

NOTE: Documentation string of the `layerFunction` passed to `CreateMethod` will
be used automatically as documentation string of the created method. Therefore,
we discourage the use of function literals here.

`*models.ExtendMethod(modelName, methodName string, layerFunction interface{})*`::
Extends the method `methodName` in the model `modelName` with the given
`layerFunction`.
+
The layer function should call the `Super()` method of its first argument to
call the previous layer, and pass it all the other arguments of the function
layer.

[source,go]
----
models.ExtendMethod("ResPartner", "UpdateBirthday",
    func(rs ResPartnerSet, birthday time.Time) {
        rs.Super(birthday)
        rs.SetAge(Time.Now().Year() - birthday.Year())
    })
----

NOTE: The `functionLayer` passed to `ExtendMethod` must have the same signature
as that of the first layer passed to `CreateMethod`.
