= Security in YEP
Author Nicolas Piganeau
:prewrap!:
:toc:

== Introduction

Security is implemented in YEP at the ORM level to limit the risks of
inappropriate privilege elevation.

=== Groups
It is based on the concept of __group__:

- Permissions are granted or denied to groups
- Groups can inherit from other groups and get access to these groups
permissions.
- A user can belong to one or several groups, and thus inherit from the
permissions of the groups.

=== Permissions

There are four permissions that can be set on models, fields or records.
They are defined in the `security` package.

[source,go]
----
type Permission uint8

const (
    Create = 1 << Permission(iota)
    Read
    Write
    Unlink
    All = Create | Read | Write | Unlink
)
----
Permissions are given to groups by two distinct mechanisms:

Access Control::
Grant permissions on models and fields

Record Rules::
Grant permissions on some records of a model only

== Access Control

Access Control defines the permissions for a group on models and fields.
They apply to all the records of a model.

=== Models Access Control

By default, a model has an access control list that only allows the members
of the AdminGroup to access it. Access Control at the model level can be set
with the `AllowModelAccess()` and `DenyModelAccess()` functions.

`*AllowModelAccess(model ModelName, group *security.Group, perm security.Permission)*`::
Grant the given `perm` permission to the given `group` for the given `model`.

[source,go]
salesManager := models.GroupsRegistry.Get("sale_manager")
models.AllowModelAccess(pool.ModelResPartner, salesManager, security.Create|security.Read)

`*DenyModelAccess(model ModelName, group *security.Group, perm security.Permission)*`::
Deny the `perm` permission to the given `group` for the given `model`.

Permissions are evaluated in the order of insertion. This means that the
overriding order of modules is preserved.

TIP: Avoid using `DenyModelAccess` whenever possible. Since no permissions are
granted by default, prefer granting permissions only to groups who need them.
This will make the application much easier to debug.

=== Fields Access Control

Only three permissions are applicable to fields: `security.Read`,
`security.Write` and 'security.Create'.

They are set by default on all fields of models which are granted
the respective permission.

Field permissions can be modified with the following functions:

`*AllowFieldAccess(model ModelName, field FieldName, group *security.Group, perm security.Permission)*`::
Grant the given `perm` to the given `group` on the given `field` of `model`.

[source,go]
salesManager := models.GroupsRegistry.Get("sale_manager")
models.AllowFieldAccess(pool.ResPartner_Function, salesManager, security.Read)

`*DenyFieldAccess(field FieldName, group *security.Group, perm security.Permission)*`::
Deny the given `perm` to the given `group` on the given `field`.

Generally speaking, the permission on the model and on the fields must match
for the action to be performed. In particular:

- When reading a record, fields without `security.Read` permission are not
retrieved and equal to their go zero value.
- When creating a record, fields without `security.Create` permission are
set to their go zero value.
- When updating a record, fields without `security.Write` permission are not
updated (silently).
- When deleting a record, fields permissions are not evaluated.

== Record Rules

=== Definition
Record Rules allow to grant or deny a group some permissions on a selection of
records. This could be the case for example to allow a salesman only to see his
own sales.

A Record Rule is a struct with the following definition, in the models package:

[source,go]
----
type RecordRule struct {
    Name      string
    Global    bool
    Group     *Group
    Condition *models.Condition
    Perms     Permission
}
----

If the `Global` field of a `RecordRule` is set, then the rule applies to all
groups and the `Group` field is ignored. The `Condition` fields is the
filter to apply on the model to retrieve the records. `Perms` define on which
operation the rule will be called. For example, if `security.Read` is set then
the rule will be applied only on reading operations. Condition value may be
functions just like any other Condition. This may be particularly useful to
get the current user.

NOTE: Setting the `security.Create` on the RecordRule has no effect since
there is no record yet during creation.

=== Adding or removing Record Rules

Record Rules are added or removed from the Record Rules Registry with the
following functions:

`*AddRecordRule(model ModelName, rule RecordRule)*`::
Register the given `RecordRule` to the registry for the given `model`. If the
rule's `Name` already exists, then the rule is overwritten.

[source,go]
----
salesman := models.GroupsRegistry.Get("sale_user")

func getUserID(rs pool.ResPartnerSet) interface{} {
    return rs.Env().Uid()
}

cond := models.NewCondition().And("User.ID", "=", getUserID)

rule := models.RecordRule {
    Name:      "salesman_own_partner",
    Group:     salesman,
    Condition: cond,
    Perms:     security.All,
}
models.AddRecordRule(pool.ModelResPartner, rule)
----

`*RemoveRecordRule(model ModelName, name string)*`::
Removes the Record Rule with the given `name` from the rule registry of the
given `model`.

[source,go]
models.RemoveRecordRule(pool.ModelResPartner, "salesman_own_partner")

=== Record Rules combination

Global rules and group rules (rules restricted to specific groups versus groups
applying to all users) are used quite differently:

* Global rules are subtractive, they must all be matched for a record to be
accessible
* Group rules are additive, if any of them matches (and all global rules match)
then the record is accessible

This means the first group rule restricts access, but any further group rule
expands it, while global rules can only ever restrict access (or have no
effect).
